import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "neutral-50": "var(--color-neutral-50)",
        "neutral-100": "var(--color-neutral-100)",
        "neutral-200": "var(--color-neutral-200)",
        "neutral-300": "var(--color-neutral-300)",
        "neutral-400": "var(--color-neutral-400)",
        "neutral-500": "var(--color-neutral-500)",
        "neutral-600": "var(--color-neutral-600)",
        "neutral-700": "var(--color-neutral-700)",
        "neutral-800": "var(--color-neutral-800)",
        "neutral-900": "var(--color-neutral-900)",
        "neutral-950": "var(--color-neutral-950)",
        "surface-base": "var(--color-surface-base)",
        "surface-raised": "var(--color-surface-raised)",
        "surface-overlay": "var(--color-surface-overlay)",
        "surface-sunken": "var(--color-surface-sunken)",
        "surface-inverse": "var(--color-surface-inverse)",
        "surface-brand-subtle": "var(--color-surface-brand-subtle)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-disabled": "var(--color-text-disabled)",
        "text-on-brand": "var(--color-text-on-brand)",
        "text-on-inverse": "var(--color-text-on-inverse)",
        "text-link": "var(--color-text-link)",
        "text-danger": "var(--color-text-danger)",
        "border-subtle": "var(--color-border-subtle)",
        "border-default": "var(--color-border-default)",
        "border-strong": "var(--color-border-strong)",
        "border-focus": "var(--color-border-focus)",
        "brand-50": "var(--color-brand-50)",
        "brand-100": "var(--color-brand-100)",
        "brand-200": "var(--color-brand-200)",
        "brand-300": "var(--color-brand-300)",
        "brand-400": "var(--color-brand-400)",
        "brand-500": "var(--color-brand-500)",
        "brand-600": "var(--color-brand-600)",
        "brand-700": "var(--color-brand-700)",
        "brand-800": "var(--color-brand-800)",
        "brand-900": "var(--color-brand-900)",
        "success-subtle": "var(--color-success-subtle)",
        "success-muted": "var(--color-success-muted)",
        "success-solid": "var(--color-success-solid)",
        "success-solid-hover": "var(--color-success-solid-hover)",
        "success-on-solid": "var(--color-success-on-solid)",
        "success-border": "var(--color-success-border)",
        "warning-subtle": "var(--color-warning-subtle)",
        "warning-muted": "var(--color-warning-muted)",
        "warning-solid": "var(--color-warning-solid)",
        "warning-solid-hover": "var(--color-warning-solid-hover)",
        "warning-on-solid": "var(--color-warning-on-solid)",
        "warning-border": "var(--color-warning-border)",
        "danger-subtle": "var(--color-danger-subtle)",
        "danger-muted": "var(--color-danger-muted)",
        "danger-solid": "var(--color-danger-solid)",
        "danger-solid-hover": "var(--color-danger-solid-hover)",
        "danger-on-solid": "var(--color-danger-on-solid)",
        "danger-border": "var(--color-danger-border)",
        "info-subtle": "var(--color-info-subtle)",
        "info-muted": "var(--color-info-muted)",
        "info-solid": "var(--color-info-solid)",
        "info-solid-hover": "var(--color-info-solid-hover)",
        "info-on-solid": "var(--color-info-on-solid)",
        "info-border": "var(--color-info-border)",
        "dv-1": "var(--color-dv-1)",
        "dv-2": "var(--color-dv-2)",
        "dv-3": "var(--color-dv-3)",
        "dv-4": "var(--color-dv-4)",
        "dv-5": "var(--color-dv-5)",
        "dv-6": "var(--color-dv-6)",
        "dv-7": "var(--color-dv-7)",
        "dv-8": "var(--color-dv-8)",
        "dv-9": "var(--color-dv-9)",
        "dv-10": "var(--color-dv-10)",
        "dv-seq-1": "var(--color-dv-seq-1)",
        "dv-seq-2": "var(--color-dv-seq-2)",
        "dv-seq-3": "var(--color-dv-seq-3)",
        "dv-seq-4": "var(--color-dv-seq-4)",
        "dv-seq-5": "var(--color-dv-seq-5)",
        "dv-seq-6": "var(--color-dv-seq-6)",
        "dv-seq-7": "var(--color-dv-seq-7)",
        "dv-seq-8": "var(--color-dv-seq-8)",
        "dv-seq-9": "var(--color-dv-seq-9)",
        "dv-div-cold": "var(--color-dv-div-cold)",
        "dv-div-mid": "var(--color-dv-div-mid)",
        "dv-div-hot": "var(--color-dv-div-hot)",
      },
      spacing: {
        0: "var(--space-0)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        0: "var(--shadow-0)",
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        overlay: "var(--shadow-overlay)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        "display-lg": [
          "var(--text-display-lg)",
          { lineHeight: "var(--leading-display-lg)", letterSpacing: "var(--tracking-display)" },
        ],
        "display-md": [
          "var(--text-display-md)",
          { lineHeight: "var(--leading-display-md)", letterSpacing: "var(--tracking-display)" },
        ],
        "heading-xl": [
          "var(--text-heading-xl)",
          { lineHeight: "var(--leading-heading-xl)", letterSpacing: "var(--tracking-heading)" },
        ],
        "heading-lg": [
          "var(--text-heading-lg)",
          { lineHeight: "var(--leading-heading-lg)", letterSpacing: "var(--tracking-heading)" },
        ],
        "heading-md": [
          "var(--text-heading-md)",
          { lineHeight: "var(--leading-heading-md)", letterSpacing: "var(--tracking-heading)" },
        ],
        "heading-sm": [
          "var(--text-heading-sm)",
          { lineHeight: "var(--leading-heading-sm)", letterSpacing: "var(--tracking-heading)" },
        ],
        "body-lg": [
          "var(--text-body-lg)",
          { lineHeight: "var(--leading-body-lg)", letterSpacing: "var(--tracking-body)" },
        ],
        "body-md": [
          "var(--text-body-md)",
          {
            lineHeight: "var(--leading-body)",
            letterSpacing: "var(--tracking-body)",
          },
        ],
        "body-sm": [
          "var(--text-body-sm)",
          { lineHeight: "var(--leading-body-sm)", letterSpacing: "var(--tracking-body)" },
        ],
        caption: [
          "var(--text-caption)",
          { lineHeight: "var(--leading-caption)", letterSpacing: "var(--tracking-caption)" },
        ],
        "code-md": [
          "var(--text-code-md)",
          { lineHeight: "var(--leading-code-md)", letterSpacing: "var(--tracking-code)" },
        ],
        "code-sm": [
          "var(--text-code-sm)",
          { lineHeight: "var(--leading-code-sm)", letterSpacing: "var(--tracking-code)" },
        ],
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        base: "var(--duration-base)",
        slow: "var(--duration-slow)",
        page: "var(--duration-page)",
      },
      transitionTimingFunction: {
        "out-quad": "var(--ease-out-quad)",
        "in-out-quad": "var(--ease-in-out-quad)",
        spring: "var(--ease-spring)",
      },
      zIndex: {
        base: "var(--z-base)",
        sticky: "var(--z-sticky)",
        topbar: "var(--z-topbar)",
        dropdown: "var(--z-dropdown)",
        "modal-backdrop": "var(--z-modal-backdrop)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
        tooltip: "var(--z-tooltip)",
      },
    },
  },
  plugins: [],
};

export default config;
