// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job.sql

package jobdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO public.jobs (
    id,
    status,
    stage,
    input_ref,
    output_ref,
    started_at,
    completed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, status, stage, input_ref, output_ref, created_at, updated_at, started_at, completed_at
`

type CreateJobParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Stage       string             `json:"stage"`
	InputRef    []byte             `json:"input_ref"`
	OutputRef   []byte             `json:"output_ref"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.InputRef,
		arg.OutputRef,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.InputRef,
		&i.OutputRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, status, stage, input_ref, output_ref, created_at, updated_at, started_at, completed_at
FROM public.jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.InputRef,
		&i.OutputRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE public.jobs
SET status = $2,
    stage = $3,
    started_at = COALESCE($4, started_at),
    completed_at = COALESCE($5, completed_at),
    output_ref = COALESCE($6, output_ref)
WHERE id = $1
RETURNING id, status, stage, input_ref, output_ref, created_at, updated_at, started_at, completed_at
`

type UpdateJobParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Stage       string             `json:"stage"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	OutputRef   []byte             `json:"output_ref"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.OutputRef,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.InputRef,
		&i.OutputRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
