// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jobdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Stage       string             `json:"stage"`
	InputRef    []byte             `json:"input_ref"`
	OutputRef   []byte             `json:"output_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}
